# Generated by Django 3.1.7 on 2021-05-25 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('replies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=400)),
                ('reply', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='replies.reply')),
            ],
        ),
    ]
