# Generated by Django 3.1.7 on 2021-06-10 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bucks', '0002_auto_20210610_1016'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
        ('ducks', '0001_initial'),
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='bass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bassCommentedOn', to='fish.bass'),
        ),
        migrations.AddField(
            model_name='comment',
            name='buck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buckCommentedOn', to='bucks.buck'),
        ),
        migrations.AddField(
            model_name='comment',
            name='duck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duckCommentedOn', to='ducks.duck'),
        ),
        migrations.AddField(
            model_name='comment',
            name='original_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentCommentedOn', to='comments.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userOwnedComment', to=settings.AUTH_USER_MODEL),
        ),
    ]
