# Generated by Django 3.1.7 on 2021-05-25 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('ducks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duck',
            name='rackpoints',
        ),
        migrations.AddField(
            model_name='duck',
            name='comments',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='commentsAboutDuck', to='comments.comment'),
        ),
    ]
