# Generated by Django 3.1.7 on 2021-06-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ducks', '0002_duck_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='duck',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
