# Generated by Django 3.1.7 on 2021-05-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ducks', '0003_auto_20210527_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='duck',
            name='footsize',
            field=models.IntegerField(default=0),
        ),
    ]
