# Generated by Django 3.1.7 on 2021-05-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ducks', '0005_auto_20210528_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duck',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='duckImages/'),
        ),
    ]
