# Generated by Django 3.1.7 on 2021-05-30 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='./buckImages/')),
                ('documents', models.FileField(blank=True, default=None, null=True, upload_to='documents/')),
                ('weight', models.IntegerField(default=0)),
                ('rackpoints', models.IntegerField(default=0)),
                ('prize', models.IntegerField(default=0)),
                ('comments', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='commentsAboutBuck', to='comments.comment')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userOwnedBuck', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
