# Generated by Django 3.1.7 on 2021-06-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='./buckImages/')),
                ('documents', models.FileField(blank=True, default=None, null=True, upload_to='documents/')),
                ('weight', models.IntegerField(default=0)),
                ('rackpoints', models.IntegerField(default=0)),
                ('prize', models.IntegerField(default=0)),
            ],
        ),
    ]
