# Generated by Django 3.1.7 on 2021-05-25 21:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bucks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Duck',
            new_name='Buck',
        ),
    ]
