# Generated by Django 3.1.7 on 2021-06-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucks', '0002_auto_20210604_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='buck',
            name='video_id',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
