# Generated by Django 3.1.7 on 2021-06-10 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bucks', '0003_auto_20210611_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buck',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userOwnedBuck', to=settings.AUTH_USER_MODEL),
        ),
    ]
