# Generated by Django 3.1.7 on 2021-05-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucks', '0004_auto_20210528_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buck',
            name='image',
            field=models.ImageField(default=None, upload_to='./buckImages/'),
        ),
    ]
