# Generated by Django 3.1.7 on 2021-06-10 21:38

from django.db import migrations, models
import fish.models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bass',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=fish.models.upload_to),
        ),
    ]
