# Generated by Django 3.1.7 on 2021-05-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bass',
            name='documents',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bass',
            name='documentsUpload',
            field=models.FileField(default=None, max_length=10000, upload_to='documentsUpload/'),
        ),
        migrations.AlterField(
            model_name='bass',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bass',
            name='imageUpload',
            field=models.ImageField(default=None, upload_to='uploads/'),
        ),
    ]
