# Generated by Django 3.1.7 on 2021-05-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_auto_20210527_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='bass',
            name='isPregnant',
            field=models.BooleanField(default=False),
        ),
    ]
