# Generated by Django 3.1.7 on 2021-05-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0003_bass_ispregnant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bass',
            name='documentsUpload',
        ),
        migrations.RemoveField(
            model_name='bass',
            name='imageUpload',
        ),
        migrations.AlterField(
            model_name='bass',
            name='documents',
            field=models.FileField(blank=True, default=None, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='bass',
            name='image',
            field=models.ImageField(default=None, upload_to='buckImages/'),
        ),
    ]
