# Generated by Django 3.1.7 on 2021-05-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0004_auto_20210528_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bass',
            name='documents',
            field=models.FileField(blank=True, default=None, null=True, upload_to='fishDocuments/'),
        ),
        migrations.AlterField(
            model_name='bass',
            name='image',
            field=models.ImageField(default=None, upload_to='fishImages/'),
        ),
    ]
