# Generated by Django 3.1.7 on 2021-05-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0006_auto_20210528_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bass',
            name='isPregnant',
            field=models.BooleanField(default=False),
        ),
    ]
